"""
Complete game data for Valtherion Online - extracted from the GDD.
Species, classes, skills (with racial/variant bonuses), 100+ crafting recipes,
items, monsters, NPCs, regions, quests, loot tables.
"""

# ============================================================
# SPECIES DATA
# ============================================================
SPECIES_DATA = {
    "Human": {
        "description": "Adaptable and resilient, humans thrive in Valtherion's cities like Aurelith and Brighthaven.",
        "stat_bonuses": {"any": 2},
        "passive": "Jack of All Trades",
        "passive_desc": "10% XP bonus from all sources. +5% chance extra Common drop from loot.",
        "terrain_bonus": None,
        "variants": {
            "Lightborne": {"stat_bonuses": {"wisdom": 3, "charisma": 2}, "passive": "Beacon of Hope", "passive_desc": "Allies within 10m gain +5% damage resistance, +10% healing received.", "alignment": "light", "threshold": 2000},
            "Shadowkin": {"stat_bonuses": {"intelligence": 3, "dexterity": 2}, "passive": "Veil of Shadows", "passive_desc": "+10% crit in low-light, +5% damage vs Light enemies.", "alignment": "dark", "threshold": 2000},
        },
    },
    "Elf": {
        "description": "Graceful and mystical, elves hail from Sylvaren and Eldergrove.",
        "stat_bonuses": {"dexterity": 3, "intelligence": 2},
        "passive": "Forest Whisper",
        "passive_desc": "+2 stealth, +10% movement speed in forests. +10% Uncommon drops in forests.",
        "terrain_bonus": "forest",
        "variants": {
            "Lumina": {"stat_bonuses": {"intelligence": 3, "wisdom": 2}, "passive": "Starlit Grace", "passive_desc": "+10% mana regen, +5% healing in forests.", "alignment": "light", "threshold": 2000},
            "Duskborn": {"stat_bonuses": {"dexterity": 3, "intelligence": 2}, "passive": "Night's Embrace", "passive_desc": "+10% spell damage at night, +5% evasion in shadows.", "alignment": "dark", "threshold": 2000},
        },
    },
    "Dwarf": {
        "description": "Stout and unyielding, dwarves dominate Zorathar and Ironwick.",
        "stat_bonuses": {"constitution": 3, "strength": 2},
        "passive": "Stonekin",
        "passive_desc": "+2 armor, 20% knockback resistance. +5% Rare drops in mines/mountains. +1 durability on gear drops.",
        "terrain_bonus": "mountain",
        "variants": {
            "Forgelight": {"stat_bonuses": {"constitution": 3, "wisdom": 2}, "passive": "Forgefather's Ward", "passive_desc": "+3 armor, +10% damage resistance below 50% HP.", "alignment": "light", "threshold": 2000},
            "Deepshadow": {"stat_bonuses": {"strength": 3, "constitution": 2}, "passive": "Cavern's Might", "passive_desc": "+10% melee damage underground, +5% crit vs stunned foes.", "alignment": "dark", "threshold": 2000},
        },
    },
    "Orc": {
        "description": "Fierce and towering, orcs roam Grimholt Bastion and the wilds of Zorathar.",
        "stat_bonuses": {"strength": 3, "constitution": 2},
        "passive": "Bloodrage",
        "passive_desc": "+10% damage below 30% HP, +5% attack speed for 10s after kill.",
        "terrain_bonus": None,
        "variants": {
            "Sunfury": {"stat_bonuses": {"strength": 3, "charisma": 2}, "passive": "Solar Wrath", "passive_desc": "+10% damage vs Dark enemies, +5% HP regen in daylight.", "alignment": "light", "threshold": 2000},
            "Nightrend": {"stat_bonuses": {"strength": 3, "dexterity": 2}, "passive": "Bloodthirst", "passive_desc": "+15% damage below 30% HP, heal 5% HP on crits.", "alignment": "dark", "threshold": 2000},
        },
    },
    "Gnome": {
        "description": "Clever and diminutive, gnomes thrive in Ironwick's workshops and Brighthaven's libraries.",
        "stat_bonuses": {"intelligence": 3, "dexterity": 2},
        "passive": "Tinker's Wit",
        "passive_desc": "+10% crafting speed, 5% material recovery on failed crafts.",
        "terrain_bonus": None,
        "variants": {
            "Brightspark": {"stat_bonuses": {"intelligence": 3, "wisdom": 2}, "passive": "Luminous Craft", "passive_desc": "+15% crafting speed, +5% spell damage with crafted weapons.", "alignment": "light", "threshold": 2000},
            "Gloomgear": {"stat_bonuses": {"intelligence": 3, "dexterity": 2}, "passive": "Dark Ingenuity", "passive_desc": "+10% damage with crafted weapons, +5% speed when stealthed.", "alignment": "dark", "threshold": 2000},
        },
    },
}

# ============================================================
# CLASS DATA
# ============================================================
CLASS_DATA = {
    "Warrior": {
        "description": "Frontline fighters specializing in melee combat and defense.",
        "primary_stats": ["strength", "constitution"],
        "base_skills": ["power_strike", "guard_stance", "bash"],
        "level_skills": {5: ["whirlwind_slash"], 10: ["rallying_cry"], 15: ["heroic_charge"]},
        "base_hp": 120, "base_mana": 30, "base_stamina": 120,
    },
    "Mage": {
        "description": "Arcane spellcasters wielding elemental and utility magic.",
        "primary_stats": ["intelligence", "wisdom"],
        "base_skills": ["magic_bolt", "mana_shield", "frost_snap"],
        "level_skills": {5: ["arcane_burst"], 10: ["chain_lightning"], 15: ["meteor_strike"]},
        "base_hp": 80, "base_mana": 100, "base_stamina": 80,
    },
    "Rogue": {
        "description": "Stealthy strikers specializing in burst damage and trickery.",
        "primary_stats": ["dexterity", "intelligence"],
        "base_skills": ["quick_slash", "smoke_veil", "dodge_roll"],
        "level_skills": {5: ["poison_dagger"], 10: ["ambush_blitz"], 15: ["assassinate"]},
        "base_hp": 90, "base_mana": 40, "base_stamina": 100,
    },
    "Cleric": {
        "description": "Holy healers and support, channeling divine power.",
        "primary_stats": ["wisdom", "constitution"],
        "base_skills": ["healing_touch", "light_ward", "smite"],
        "level_skills": {5: ["divine_pulse"], 10: ["purifying_light"], 15: ["serenitys_embrace"]},
        "base_hp": 100, "base_mana": 80, "base_stamina": 90,
    },
    "Ranger": {
        "description": "Ranged specialists excelling at traps, bows, and tracking.",
        "primary_stats": ["dexterity", "wisdom"],
        "base_skills": ["aimed_shot", "snare_trap", "evasive_leap"],
        "level_skills": {5: ["barrage_shot"], 10: ["hunters_mark"], 15: ["explosive_volley"]},
        "base_hp": 95, "base_mana": 50, "base_stamina": 100,
    },
}

# ============================================================
# SKILL DATA (with racial bonuses and variant bonuses)
# ============================================================
SKILL_DATA = {
    # === WARRIOR ===
    "power_strike": {
        "name": "Power Strike", "class": "Warrior", "min_level": 1,
        "scaling_stat": "strength", "damage_multiplier": 1.5,
        "stamina_cost": 10, "mana_cost": 0, "cooldown": 6,
        "description": "A mighty swing dealing bonus damage. +2 damage if target is below 50% HP.",
        "racial_bonus": {"Human": "cooldown_5s", "Elf": "range_2blocks", "Dwarf": "armor_1_3s", "Orc": "damage_2_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "heal_1_on_hit", "dark": "crit_chance_2"},
    },
    "guard_stance": {
        "name": "Guard Stance", "class": "Warrior", "min_level": 1,
        "scaling_stat": "constitution", "armor_bonus": 2,
        "stamina_cost": 5, "mana_cost": 0, "cooldown": 10, "duration": 5,
        "description": "Enter a defensive stance. +2 armor, draws enemy aggression within 3 blocks.",
        "racial_bonus": {"Human": "duration_5.5s", "Elf": "dex_1", "Dwarf": "armor_3", "Orc": "damage_5pct", "Gnome": "armor_1_crafted"},
        "variant_boost": {"light": "ally_resist_5pct", "dark": "damage_reduction_1"},
    },
    "bash": {
        "name": "Bash", "class": "Warrior", "min_level": 1,
        "scaling_stat": "strength", "damage_multiplier": 0.8,
        "stamina_cost": 8, "mana_cost": 0, "cooldown": 8, "knockback": 1,
        "description": "Smash target, knocking back 1 block.",
        "racial_bonus": {"Human": "cooldown_7s", "Elf": "knockback_2", "Dwarf": "slow_1s", "Orc": "damage_2_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "armor_1_post", "dark": "heal_2_on_hit"},
    },
    "whirlwind_slash": {
        "name": "Whirlwind Slash", "class": "Warrior", "min_level": 5,
        "scaling_stat": "strength", "damage_multiplier": 1.2,
        "stamina_cost": 15, "mana_cost": 0, "cooldown": 12, "aoe_radius": 3,
        "description": "Spin attack hitting all enemies within 3 blocks. 8-12 damage.",
        "racial_bonus": {"Human": "cooldown_reset_10pct", "Elf": "radius_4", "Dwarf": "damage_resist_2", "Orc": "damage_3_low_hp", "Gnome": "damage_2_crafted"},
        "variant_boost": {"light": "damage_5pct_vs_dark", "dark": "trap_synergy_1"},
    },
    "rallying_cry": {
        "name": "Rallying Cry", "class": "Warrior", "min_level": 10,
        "scaling_stat": "charisma", "attack_bonus": 3,
        "stamina_cost": 10, "mana_cost": 0, "cooldown": 15, "duration": 6, "radius": 5,
        "description": "Boost allies within 5 blocks with +3 attack for 6s.",
        "racial_bonus": {"Human": "cooldown_13s", "Elf": "range_7", "Dwarf": "ally_armor_1", "Orc": "attack_1_low_hp", "Gnome": "craft_speed_10pct"},
        "variant_boost": {"light": "hp_regen_2", "dark": "damage_1"},
    },
    "heroic_charge": {
        "name": "Heroic Charge", "class": "Warrior", "min_level": 15,
        "scaling_stat": "strength", "damage_multiplier": 2.0,
        "stamina_cost": 20, "mana_cost": 0, "cooldown": 20, "range": 8, "stun": 1,
        "description": "Charge 8 blocks dealing 12-18 damage, stunning for 1s.",
        "racial_bonus": {"Human": "damage_10pct_per_ally", "Elf": "range_10", "Dwarf": "knockback_2", "Orc": "damage_5_low_hp", "Gnome": "damage_3_crafted"},
        "variant_boost": {"light": "armor_2_post", "dark": "heal_5_on_hit"},
    },

    # === MAGE ===
    "magic_bolt": {
        "name": "Magic Bolt", "class": "Mage", "min_level": 1,
        "scaling_stat": "intelligence", "damage_multiplier": 1.6,
        "stamina_cost": 0, "mana_cost": 10, "cooldown": 5, "range": 10, "damage_type": "arcane",
        "description": "Fire a bolt of arcane energy 10 blocks.",
        "racial_bonus": {"Human": "cooldown_4s", "Elf": "range_12", "Dwarf": "armor_1_3s", "Orc": "damage_2_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "heal_1", "dark": "crit_chance_2"},
    },
    "mana_shield": {
        "name": "Mana Shield", "class": "Mage", "min_level": 1,
        "scaling_stat": "intelligence",
        "stamina_cost": 0, "mana_cost": 20, "cooldown": 10, "absorb": 8, "duration": 5,
        "description": "Absorbs 8 damage for 5s.",
        "racial_bonus": {"Human": "duration_5.5s", "Elf": "dex_1", "Dwarf": "absorb_10", "Orc": "damage_5pct", "Gnome": "absorb_2_crafted"},
        "variant_boost": {"light": "armor_1", "dark": "cooldown_minus_1"},
    },
    "frost_snap": {
        "name": "Frost Snap", "class": "Mage", "min_level": 3,
        "scaling_stat": "intelligence", "damage_multiplier": 1.3,
        "stamina_cost": 0, "mana_cost": 15, "cooldown": 8, "damage_type": "ice", "cone": 3, "slow": 20, "slow_duration": 3,
        "description": "Chill a 3-block cone, slowing enemies by 20% for 3s.",
        "racial_bonus": {"Human": "cooldown_7s", "Elf": "cone_4", "Dwarf": "damage_2", "Orc": "damage_1_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "slow_duration_1", "dark": "damage_1_night"},
    },
    "arcane_burst": {
        "name": "Arcane Burst", "class": "Mage", "min_level": 5,
        "scaling_stat": "intelligence", "damage_multiplier": 1.8,
        "stamina_cost": 0, "mana_cost": 25, "cooldown": 10, "aoe_radius": 3, "splash_damage": 0.5,
        "description": "Blast 10-14 damage with 3-block splash.",
        "racial_bonus": {"Human": "cooldown_8s", "Elf": "radius_4", "Dwarf": "armor_2_5s", "Orc": "damage_3_low_hp", "Gnome": "damage_2_crafted"},
        "variant_boost": {"light": "heal_splash_1", "dark": "trap_synergy_1"},
    },
    "chain_lightning": {
        "name": "Chain Lightning", "class": "Mage", "min_level": 10,
        "scaling_stat": "intelligence", "damage_multiplier": 1.5,
        "stamina_cost": 0, "mana_cost": 30, "cooldown": 15, "chains": 3, "chain_range": 5,
        "description": "Zaps 10-15 damage, chaining to 3 foes within 5 blocks.",
        "racial_bonus": {"Human": "cooldown_13s", "Elf": "chain_range_7", "Dwarf": "first_hit_5", "Orc": "chain_damage_2_low_hp", "Gnome": "chain_1_extra_crafted"},
        "variant_boost": {"light": "heal_1_per_chain", "dark": "crit_chance_1"},
    },
    "meteor_strike": {
        "name": "Meteor Strike", "class": "Mage", "min_level": 15,
        "scaling_stat": "intelligence", "damage_multiplier": 2.5,
        "stamina_cost": 0, "mana_cost": 50, "cooldown": 20, "aoe_radius": 4, "range": 15,
        "description": "Crashes 15-25 damage in a 4-block AoE at 15-block range.",
        "racial_bonus": {"Human": "stun_10pct", "Elf": "radius_5", "Dwarf": "burn_5_damage_3s", "Orc": "damage_5_low_hp", "Gnome": "damage_3_crafted"},
        "variant_boost": {"light": "heal_aoe_2", "dark": "damage_5_night"},
    },

    # === ROGUE ===
    "quick_slash": {
        "name": "Quick Slash", "class": "Rogue", "min_level": 1,
        "scaling_stat": "dexterity", "damage_multiplier": 1.3,
        "stamina_cost": 8, "mana_cost": 0, "cooldown": 5,
        "description": "A rapid slash. +2 damage if stealthed.",
        "racial_bonus": {"Human": "cooldown_4s", "Elf": "stealth_bonus_3", "Dwarf": "armor_1_3s", "Orc": "damage_2_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "heal_1", "dark": "crit_chance_2"},
    },
    "smoke_veil": {
        "name": "Smoke Veil", "class": "Rogue", "min_level": 1,
        "scaling_stat": "dexterity", "stealth_bonus": 3,
        "stamina_cost": 12, "mana_cost": 0, "cooldown": 10, "duration": 4,
        "description": "Grants +3 stealth for 4s. Breaks on attack.",
        "racial_bonus": {"Human": "speed_10pct", "Elf": "duration_5s", "Dwarf": "damage_reduce_1", "Orc": "damage_5pct_after", "Gnome": "stealth_1_crafted"},
        "variant_boost": {"light": "trap_range_1", "dark": "speed_5pct_shadows"},
    },
    "dodge_roll": {
        "name": "Dodge Roll", "class": "Rogue", "min_level": 1,
        "scaling_stat": "dexterity",
        "stamina_cost": 10, "mana_cost": 0, "cooldown": 8, "dash_range": 3, "evasion_duration": 1,
        "description": "Dash 3 blocks, evading attacks for 1s.",
        "racial_bonus": {"Human": "cooldown_7s", "Elf": "range_4", "Dwarf": "armor_1_3s", "Orc": "damage_5pct_3s", "Gnome": "range_1_crafted"},
        "variant_boost": {"light": "armor_1", "dark": "heal_2"},
    },
    "poison_dagger": {
        "name": "Poison Dagger", "class": "Rogue", "min_level": 5,
        "scaling_stat": "dexterity", "damage_multiplier": 1.5, "poison_damage": 3, "poison_duration": 5,
        "stamina_cost": 12, "mana_cost": 0, "cooldown": 10,
        "description": "Slashes 8-12 damage + 3 poison/sec for 5s.",
        "racial_bonus": {"Human": "cooldown_8s", "Elf": "poison_duration_6s", "Dwarf": "damage_2_initial", "Orc": "poison_2_low_hp", "Gnome": "poison_1_crafted"},
        "variant_boost": {"light": "damage_1_vs_dark", "dark": "trap_synergy_1"},
    },
    "ambush_blitz": {
        "name": "Ambush Blitz", "class": "Rogue", "min_level": 10,
        "scaling_stat": "dexterity", "damage_multiplier": 1.8, "unaware_bonus": 5,
        "stamina_cost": 18, "mana_cost": 0, "cooldown": 15, "dash_range": 5,
        "description": "Dashes 5 blocks dealing 10-15 damage. +5 if target is unaware.",
        "racial_bonus": {"Human": "cooldown_13s", "Elf": "dash_7", "Dwarf": "slow_2s", "Orc": "damage_3_low_hp", "Gnome": "damage_2_crafted"},
        "variant_boost": {"light": None, "dark": "heal_3_on_hit"},
    },
    "assassinate": {
        "name": "Assassinate", "class": "Rogue", "min_level": 15,
        "scaling_stat": "dexterity", "damage_multiplier": 2.8, "low_hp_bonus": 10,
        "stamina_cost": 25, "mana_cost": 0, "cooldown": 20,
        "description": "Deals 15-25 damage from stealth. +10 if target is below 50% HP.",
        "racial_bonus": {"Human": "crit_10pct", "Elf": "damage_5_forests", "Dwarf": "ignore_3_armor", "Orc": "damage_5_low_hp", "Gnome": "damage_3_crafted"},
        "variant_boost": {"light": "heal_2", "dark": "crit_damage_5"},
    },

    # === CLERIC ===
    "healing_touch": {
        "name": "Healing Touch", "class": "Cleric", "min_level": 1,
        "scaling_stat": "wisdom", "heal_multiplier": 1.5,
        "stamina_cost": 0, "mana_cost": 15, "cooldown": 6, "range": 5,
        "description": "Restores 5-8 HP to one ally within 5 blocks.",
        "racial_bonus": {"Human": "cooldown_5s", "Elf": "range_7", "Dwarf": "armor_1_to_target", "Orc": "heal_2_low_hp", "Gnome": "heal_1_crafted"},
        "variant_boost": {"light": "heal_2", "dark": "damage_1"},
    },
    "light_ward": {
        "name": "Light Ward", "class": "Cleric", "min_level": 1,
        "scaling_stat": "wisdom", "armor_bonus": 2,
        "stamina_cost": 0, "mana_cost": 12, "cooldown": 8, "duration": 5, "range": 5,
        "description": "Grant +2 armor to a target for 5s.",
        "racial_bonus": {"Human": "duration_5.5s", "Elf": "dex_1_to_target", "Dwarf": "armor_3", "Orc": "damage_5pct_to_target", "Gnome": "armor_1_crafted"},
        "variant_boost": {"light": "duration_1", "dark": "damage_1_after"},
    },
    "smite": {
        "name": "Smite", "class": "Cleric", "min_level": 1,
        "scaling_stat": "wisdom", "damage_multiplier": 1.2,
        "stamina_cost": 0, "mana_cost": 10, "cooldown": 7, "range": 5, "damage_type": "light",
        "description": "Deal 4-6 light damage to an enemy.",
        "racial_bonus": {"Human": "cooldown_6s", "Elf": "range_7", "Dwarf": "damage_2", "Orc": "damage_1_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "damage_2_vs_dark", "dark": "crit_chance_1"},
    },
    "divine_pulse": {
        "name": "Divine Pulse", "class": "Cleric", "min_level": 5,
        "scaling_stat": "wisdom", "heal_multiplier": 0.8,
        "stamina_cost": 0, "mana_cost": 25, "cooldown": 10, "radius": 5,
        "description": "Heal 8-12 HP to all allies within 5 blocks.",
        "racial_bonus": {"Human": "cooldown_8s", "Elf": "range_7", "Dwarf": "ally_armor_1_5s", "Orc": "heal_2_low_hp", "Gnome": "heal_1_crafted"},
        "variant_boost": {"light": "heal_2_forest", "dark": "damage_1"},
    },
    "purifying_light": {
        "name": "Purifying Light", "class": "Cleric", "min_level": 10,
        "scaling_stat": "wisdom", "damage_multiplier": 1.5, "cleanses_debuffs": True,
        "stamina_cost": 0, "mana_cost": 30, "cooldown": 15, "radius": 5,
        "description": "Deal 10-15 light damage and remove debuffs in 5-block radius.",
        "racial_bonus": {"Human": "cooldown_13s", "Elf": "radius_6", "Dwarf": "heal_5", "Orc": "damage_3_low_hp", "Gnome": "damage_2_crafted"},
        "variant_boost": {"light": "damage_3_vs_dark", "dark": "trap_synergy_1"},
    },
    "serenitys_embrace": {
        "name": "Serenity's Embrace", "class": "Cleric", "min_level": 15,
        "scaling_stat": "wisdom", "heal_multiplier": 1.5, "attack_bonus": 4,
        "stamina_cost": 0, "mana_cost": 45, "cooldown": 20, "radius": 8, "duration": 6,
        "description": "Heal 12-20 HP and grant +4 attack to allies within 8 blocks for 6s.",
        "racial_bonus": {"Human": "heal_potency_10pct", "Elf": "range_10", "Dwarf": "ally_armor_2", "Orc": "attack_2_low_hp", "Gnome": "heal_2_crafted"},
        "variant_boost": {"light": "duration_2", "dark": "damage_2"},
    },

    # === RANGER ===
    "aimed_shot": {
        "name": "Aimed Shot", "class": "Ranger", "min_level": 1,
        "scaling_stat": "dexterity", "damage_multiplier": 1.4, "still_bonus": 2,
        "stamina_cost": 8, "mana_cost": 0, "cooldown": 6, "range": 12,
        "description": "Fire 5-8 damage at 12-block range. +2 if target is stationary.",
        "racial_bonus": {"Human": "cooldown_5s", "Elf": "range_14", "Dwarf": "damage_1", "Orc": "damage_2_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "damage_1_vs_dark", "dark": "crit_chance_2"},
    },
    "snare_trap": {
        "name": "Snare Trap", "class": "Ranger", "min_level": 1,
        "scaling_stat": "dexterity", "damage_multiplier": 0.5, "root_duration": 3,
        "stamina_cost": 10, "mana_cost": 0, "cooldown": 10, "range": 5,
        "description": "Set a trap that roots enemy for 3s and deals 3-5 damage.",
        "racial_bonus": {"Human": "duration_3.3s", "Elf": "range_7", "Dwarf": "damage_2", "Orc": "damage_1_low_hp", "Gnome": "duration_1_crafted"},
        "variant_boost": {"light": "range_1", "dark": "damage_1_underground"},
    },
    "evasive_leap": {
        "name": "Evasive Leap", "class": "Ranger", "min_level": 1,
        "scaling_stat": "dexterity",
        "stamina_cost": 10, "mana_cost": 0, "cooldown": 8, "leap_range": 4, "evasion_bonus": 2, "evasion_duration": 3,
        "description": "Jump back 4 blocks, gaining +2 evasion for 3s.",
        "racial_bonus": {"Human": "cooldown_7s", "Elf": "range_5", "Dwarf": "armor_1_3s", "Orc": "damage_5pct_3s", "Gnome": "range_1_crafted"},
        "variant_boost": {"light": "duration_1", "dark": "damage_1_after"},
    },
    "barrage_shot": {
        "name": "Barrage Shot", "class": "Ranger", "min_level": 5,
        "scaling_stat": "dexterity", "damage_multiplier": 0.9, "arrows": 3,
        "stamina_cost": 14, "mana_cost": 0, "cooldown": 10, "range": 12,
        "description": "Fire 3 arrows, 6-9 damage each at 12-block range.",
        "racial_bonus": {"Human": "cooldown_8s", "Elf": "range_14", "Dwarf": "damage_2_per_arrow", "Orc": "damage_1_low_hp", "Gnome": "damage_1_crafted"},
        "variant_boost": {"light": "range_1", "dark": "crit_chance_1"},
    },
    "hunters_mark": {
        "name": "Hunter's Mark", "class": "Ranger", "min_level": 10,
        "scaling_stat": "wisdom", "damage_taken_bonus": 15,
        "stamina_cost": 0, "mana_cost": 15, "cooldown": 15, "range": 15, "duration": 8,
        "description": "Mark a target for 8s. Marked target takes 15% increased damage.",
        "racial_bonus": {"Human": "cooldown_13s", "Elf": "range_18", "Dwarf": "next_shot_5", "Orc": "bonus_5pct_low_hp", "Gnome": "duration_2_crafted"},
        "variant_boost": {"light": "damage_5pct_vs_dark", "dark": "trap_synergy_1"},
    },
    "explosive_volley": {
        "name": "Explosive Volley", "class": "Ranger", "min_level": 15,
        "scaling_stat": "dexterity", "damage_multiplier": 2.0,
        "stamina_cost": 22, "mana_cost": 0, "cooldown": 20, "aoe_radius": 4, "range": 15,
        "description": "Fire an explosive arrow dealing 12-20 damage in a 4-block AoE.",
        "racial_bonus": {"Human": "cooldown_reset_10pct", "Elf": "radius_5", "Dwarf": "burn_5_3s", "Orc": "damage_5_low_hp", "Gnome": "damage_3_crafted"},
        "variant_boost": {"light": "heal_aoe_2", "dark": "crit_damage_5"},
    },

    # === UNIVERSAL SKILLS ===
    "swift_step": {
        "name": "Swift Step", "class": "Universal", "min_level": 1,
        "stamina_cost": 5, "mana_cost": 0, "cooldown": 15, "speed_boost": 20, "duration": 5,
        "description": "Boost movement speed by 20% for 5s.",
        "acquisition": "Purchase from Scout NPCs (50 Zirdun) or quest 'Outrun the Prowlers'",
    },
    "minor_regen": {
        "name": "Minor Regen", "class": "Universal", "min_level": 1,
        "stamina_cost": 0, "mana_cost": 10, "cooldown": 20, "heal_per_sec": 2, "duration": 5,
        "description": "Heal 2 HP/sec for 5s.",
        "acquisition": "Purchase from Healer NPCs (40 Zirdun) or quest 'Tend the Wounded'",
    },
    "quick_block": {
        "name": "Quick Block", "class": "Universal", "min_level": 1,
        "stamina_cost": 5, "mana_cost": 0, "cooldown": 12, "damage_reduction": 5, "duration": 3,
        "description": "Reduce next incoming damage by 5 for 3s.",
        "acquisition": "Purchase from Guard NPCs (45 Zirdun) or quest 'Hold the Line'",
    },
    "battle_roar": {
        "name": "Battle Roar", "class": "Universal", "min_level": 5,
        "stamina_cost": 15, "mana_cost": 0, "cooldown": 25, "attack_bonus": 5, "duration": 8, "radius": 5,
        "description": "Grant +5 attack to self and allies within 5 blocks for 8s.",
        "acquisition": "Drop: Grubstake Bandit Chief (Lv15) or quest 'Rally the Troops'",
    },
    "adrenaline_rush": {
        "name": "Adrenaline Rush", "class": "Universal", "min_level": 10,
        "stamina_cost": 20, "mana_cost": 0, "cooldown": 30, "attack_speed": 10, "speed_boost": 10, "duration": 10,
        "description": "+10% attack and movement speed for 10s.",
        "acquisition": "Drop: Spectral Hound Alpha (Lv20) or quest 'Push the Limits'",
    },
}

# ============================================================
# 100 CRAFTING RECIPES (from GDD)
# ============================================================
CRAFTING_RECIPES = {
    "blacksmithing": [
        # Warrior Recipes
        {"id": 1, "result": "trollbone_cleaver", "name": "Trollbone Cleaver", "level": 5, "rarity": "Rare",
         "materials": {"cracked_armor_shards": 5, "cragborn_troll_bones": 2, "kupdun": 50},
         "stats": {"attack": 8, "armor_penetration": 2, "strength": 1},
         "description": "A jagged blade carved from a troll's femur, its rough edge tears through armor.",
         "rumor": "Heard from a Stonegale Smith: 'Troll bones make blades that bite deeper than iron.'",
         "xp": 35, "time": 12},
        {"id": 2, "result": "emberforge_shield", "name": "Emberforge Shield", "level": 5, "rarity": "Uncommon",
         "materials": {"ember_scales": 3, "broken_iron_shield": 1, "kupdun": 40},
         "stats": {"armor": 5, "fire_resistance": 10, "constitution": 1},
         "description": "A round shield tempered with volcanic scales, glowing faintly with Emberfield's heat.",
         "rumor": "A Kaltheron Forgemaster mutters: 'Scales from the firelands shield better than steel.'",
         "xp": 25, "time": 8},
        {"id": 3, "result": "ironclad_gauntlets", "name": "Ironclad Gauntlets", "level": 10, "rarity": "Uncommon",
         "materials": {"iron_ore": 4, "kobold_claws": 2, "worn_iron_helm": 1, "zirdun": 80},
         "stats": {"attack": 5, "armor": 2, "strength": 2},
         "description": "Heavy gauntlets forged from Ironwick's deepest ores.",
         "rumor": "A Kaltheron Miner boasts: 'Iron from the deep makes fists like hammers.'",
         "xp": 45, "time": 10},
        {"id": 4, "result": "stormbreaker_axe", "name": "Stormbreaker Axe", "level": 15, "rarity": "Epic",
         "materials": {"stormtalon_fragments": 3, "mithril_vein": 5, "ironscale_drake_scale": 1, "zirdun": 150},
         "stats": {"attack": 15, "thunder_damage": 5, "strength": 3},
         "description": "A massive axe etched with Zorathar's storm runes, crackling with thunder.",
         "rumor": "A Stonegale Elder whispers: 'An axe born of storms awaits the drake-slayer.'",
         "xp": 150, "time": 20},
        {"id": 21, "result": "stonekin_breastplate", "name": "Stonekin Breastplate", "level": 5, "rarity": "Uncommon",
         "materials": {"cracked_armor_shards": 4, "broken_iron_shield": 1, "kupdun": 60},
         "stats": {"armor": 6, "constitution": 2},
         "description": "Rugged chestplate hammered from Stonegale's shattered armor.",
         "xp": 20, "time": 8},
        {"id": 22, "result": "banditbane_sword", "name": "Banditbane Sword", "level": 10, "rarity": "Rare",
         "materials": {"bandit_sashes": 3, "iron_ore": 2, "rusty_shortsword": 1, "zirdun": 100},
         "stats": {"attack": 10, "npc_damage_bonus": 3},
         "description": "A keen-edged blade forged from bandit spoils.",
         "xp": 50, "time": 10},
        {"id": 23, "result": "drakeforged_helm", "name": "Drakeforged Helm", "level": 15, "rarity": "Epic",
         "materials": {"ironscale_drake_scales": 2, "mithril_vein": 5, "worn_iron_helm": 1, "zirdun": 150},
         "stats": {"armor": 8, "hp": 15},
         "description": "A formidable helm shaped from Grimholt Bastion's drakes.",
         "xp": 100, "time": 15},
        {"id": 24, "result": "marauders_greaves", "name": "Marauder's Greaves", "level": 10, "rarity": "Uncommon",
         "materials": {"cracked_armor_shards": 3, "ember_scales": 2, "zirdun": 90},
         "stats": {"armor": 5, "knockback_resistance": 5, "constitution": 1},
         "description": "Sturdy leg guards from Stonegale's marauder spoils.",
         "xp": 35, "time": 8},
        {"id": 25, "result": "trollfury_hammer", "name": "Trollfury Hammer", "level": 15, "rarity": "Epic",
         "materials": {"cragborn_troll_bones": 3, "mithril_vein": 4, "broken_mace": 1, "zirdun": 180},
         "stats": {"attack": 14, "large_foe_damage": 5, "strength": 2},
         "description": "A massive warhammer carved from Zorathar's troll bones.",
         "xp": 120, "time": 18},
    ],
    "alchemy": [
        {"id": 10, "result": "potion_vitality", "name": "Potion of Vitality", "level": 1, "rarity": "Common",
         "materials": {"duskpetal": 3, "water": 1}, "stats": {"health_restore": 50},
         "description": "A crimson potion that restores vital energy.",
         "xp": 8, "time": 3},
        {"id": 11, "result": "mana_elixir", "name": "Mana Elixir", "level": 1, "rarity": "Common",
         "materials": {"liquid_slime": 2, "water": 1}, "stats": {"mana_restore": 30},
         "description": "A azure elixir that replenishes magical essence.",
         "xp": 8, "time": 3},
        {"id": 12, "result": "stamina_potion", "name": "Stamina Potion", "level": 3, "rarity": "Common",
         "materials": {"emberbloom": 3, "water": 1}, "stats": {"stamina_restore": 40},
         "description": "A green potion that restores physical endurance.",
         "xp": 12, "time": 4},
        {"id": 13, "result": "antidote", "name": "Antidote", "level": 3, "rarity": "Common",
         "materials": {"duskpetal": 2, "water": 1, "liquid_slime": 1}, "stats": {"cures_poison": True},
         "description": "Neutralizes venom from Valtherion's toxic creatures.",
         "xp": 10, "time": 3},
        {"id": 14, "result": "elixir_of_strength", "name": "Elixir of Strength", "level": 8, "rarity": "Uncommon",
         "materials": {"emberbloom": 5, "cragborn_troll_bones": 1, "water": 2},
         "stats": {"strength_boost": 5, "duration": 300},
         "description": "Temporarily boosts physical power.",
         "xp": 25, "time": 8},
    ],
    "fletching": [
        {"id": 20, "result": "basic_arrows", "name": "Basic Arrows x20", "level": 1, "rarity": "Common",
         "materials": {"wood": 3, "iron_ore": 1}, "stats": {},
         "description": "Simple arrows for hunting and combat.",
         "xp": 5, "time": 3},
        {"id": 31, "result": "ironback_longbow", "name": "Ironback Longbow", "level": 5, "rarity": "Uncommon",
         "materials": {"ironback_hides": 3, "iron_ore": 2, "wood": 3, "kupdun": 50},
         "stats": {"attack": 7, "range": 2, "dexterity": 1},
         "description": "A sturdy bow crafted from Wheatshadow boar hide.",
         "rumor": "A Wheatshadow Hunter grunts: 'Boar hide bends a bow truer than oak.'",
         "xp": 25, "time": 8},
        {"id": 32, "result": "spectral_volley_bow", "name": "Spectral Volley Bow", "level": 15, "rarity": "Epic",
         "materials": {"spectral_hound_fangs": 2, "mithril_vein": 5, "ironback_longbow": 1, "zirdun": 180},
         "stats": {"attack": 14, "spectral_damage": 10, "dexterity": 3},
         "description": "A ghostly bow infused with Frostmead's hound spirits.",
         "xp": 120, "time": 18},
        {"id": 33, "result": "stormtalon_longbow", "name": "Stormtalon Longbow", "level": 10, "rarity": "Rare",
         "materials": {"stormtalon_fragments": 3, "iron_ore": 2, "bogwood_recurve": 1, "zirdun": 100},
         "stats": {"attack": 10, "thunder_damage": 5, "dexterity": 2},
         "description": "A powerful bow forged from Stonegale's marauder axes.",
         "xp": 60, "time": 12},
        {"id": 34, "result": "emberthorn_recurve", "name": "Emberthorn Recurve", "level": 15, "rarity": "Epic",
         "materials": {"ember_scales": 3, "wraithvine_tendrils": 3, "ironback_longbow": 1, "zirdun": 200},
         "stats": {"attack": 14, "fire_damage": 7, "dexterity": 3},
         "description": "A sleek recurve bow blazing a trail of ruin.",
         "xp": 130, "time": 18},
    ],
    "leatherworking": [
        {"id": 40, "result": "leather_armor", "name": "Leather Armor", "level": 1, "rarity": "Common",
         "materials": {"animal_hide": 5, "thread": 2}, "stats": {"armor": 2},
         "description": "Basic protection for the aspiring adventurer.",
         "xp": 8, "time": 4},
        {"id": 41, "result": "slinkcloak_hood", "name": "Slinkcloak Hood", "level": 5, "rarity": "Uncommon",
         "materials": {"bandit_sashes": 3, "tattered_cloth": 1, "kupdun": 40},
         "stats": {"stealth": 4, "armor": 2, "dexterity": 1},
         "description": "A hooded cape blending into shadows with ease.",
         "rumor": "A Thornskull Smuggler grins: 'Bandit rags hide you better than night.'",
         "xp": 20, "time": 6},
        {"id": 42, "result": "shadowveil_cloak", "name": "Shadowveil Cloak", "level": 5, "rarity": "Uncommon",
         "materials": {"gloom_silk": 3, "animal_hide": 2, "thread": 2, "kupdun": 50},
         "stats": {"stealth": 3, "armor": 2, "dexterity": 1},
         "description": "A cloak spun from Shadowfen's arachnid silk.",
         "xp": 25, "time": 8},
        {"id": 43, "result": "prowlerhide_vest", "name": "Prowlerhide Vest", "level": 10, "rarity": "Rare",
         "materials": {"shadowclaw_pelts": 4, "ironback_hides": 2, "thread": 3, "zirdun": 100},
         "stats": {"armor": 5, "crit_chance": 5},
         "description": "A tough vest stitched from Frostmead's prowler pelts.",
         "xp": 50, "time": 10},
        {"id": 44, "result": "swiftantler_boots", "name": "Swiftantler Boots", "level": 5, "rarity": "Uncommon",
         "materials": {"swiftantler_antlers": 2, "tattered_cloth": 1, "kupdun": 40},
         "stats": {"armor": 3, "movement_speed": 10, "dexterity": 1},
         "description": "Light boots granting fleet-footed grace.",
         "xp": 18, "time": 5},
    ],
    "enchanting": [
        {"id": 50, "result": "minor_fire_enchant", "name": "Minor Fire Enchantment", "level": 1, "rarity": "Common",
         "materials": {"ember_scales": 2, "spectral_dust": 1},
         "stats": {"fire_damage": 3, "enchant_slot": "weapon"},
         "description": "Enchants a weapon with minor fire damage.",
         "xp": 15, "time": 5},
        {"id": 51, "result": "minor_ice_enchant", "name": "Minor Ice Enchantment", "level": 3, "rarity": "Common",
         "materials": {"frostgore_shards": 1, "spectral_dust": 2},
         "stats": {"ice_damage": 3, "enchant_slot": "weapon"},
         "description": "Enchants a weapon with minor ice damage.",
         "xp": 20, "time": 6},
        {"id": 52, "result": "rune_of_power", "name": "Rune of Power", "level": 10, "rarity": "Rare",
         "materials": {"mithril_vein": 3, "spectral_dust": 5, "gloom_silk": 2, "zirdun": 100},
         "stats": {"spell_damage": 5, "enchant_slot": "staff"},
         "description": "A rune that amplifies arcane power.",
         "xp": 60, "time": 12},
        {"id": 53, "result": "soulshatter_enchant", "name": "Soulshatter Enchantment", "level": 15, "rarity": "Legendary",
         "materials": {"mithril_vein": 6, "spectral_dust": 10, "wraithvine_tendrils": 2, "zirdun": 200},
         "stats": {"all_damage": 8, "enchant_slot": "weapon"},
         "description": "The ultimate weapon enchantment, said to bind Zorvathax's power.",
         "xp": 150, "time": 20},
    ],
    "cooking": [
        {"id": 60, "result": "bread", "name": "Bread Loaf", "level": 1, "rarity": "Common",
         "materials": {"wheat": 2, "water": 1}, "stats": {"health_restore": 10, "hunger_restore": 15},
         "description": "A simple but filling loaf.",
         "xp": 3, "time": 2},
        {"id": 61, "result": "hearty_stew", "name": "Hearty Stew", "level": 5, "rarity": "Uncommon",
         "materials": {"meat": 3, "wheat": 1, "water": 1, "emberbloom": 1},
         "stats": {"health_restore": 25, "hunger_restore": 20},
         "description": "A warm stew that restores body and spirit.",
         "xp": 12, "time": 5},
        {"id": 62, "result": "warriors_feast", "name": "Warrior's Feast", "level": 10, "rarity": "Rare",
         "materials": {"meat": 5, "wheat": 2, "emberbloom": 2, "duskpetal": 1},
         "stats": {"health_restore": 50, "hunger_restore": 30, "stamina_restore": 20},
         "description": "A grand meal worthy of Valtherion's champions.",
         "xp": 30, "time": 10},
    ],
}

# ============================================================
# ITEM RARITY TIERS
# ============================================================
ITEM_RARITIES = {
    "Common": {"color": "White", "drop_chance": 0.60, "shadow": "#ffffff"},
    "Uncommon": {"color": "Green", "drop_chance": 0.25, "shadow": "#00ff00"},
    "Rare": {"color": "Blue", "drop_chance": 0.10, "shadow": "#0088ff"},
    "Epic": {"color": "Purple", "drop_chance": 0.05, "shadow": "#aa00ff"},
    "Legendary": {"color": "Orange", "drop_chance": 0.01, "shadow": "#ff8800"},
    "God-Tier": {"color": "Red", "drop_chance": 0.001, "shadow": "#ff0000"},
}

# ============================================================
# REGIONS
# ============================================================
REGIONS_DATA = [
    {"name": "Murkfen Hamlet", "description": "A misty bogland village where new adventurers begin their journey.", "climate": "swamp", "danger_level": 1, "min_level": 1, "max_level": 5, "connections": ["Shadowfen Bog", "Wheatshadow Fields"], "ambient_lighting": {"fog_density": 0.7, "sun_color": [0.5, 0.6, 0.4], "fog_color": [0.4, 0.5, 0.3]}, "music_track": "murkfen_ambient", "pvp_enabled": False},
    {"name": "Shadowfen Bog", "description": "Murky waters bubble beneath a shroud of gray mist, illuminated by will-o'-wisps.", "climate": "swamp", "danger_level": 2, "min_level": 2, "max_level": 8, "connections": ["Murkfen Hamlet", "Sylvaren Forest", "Duskwind"], "ambient_lighting": {"fog_density": 0.9, "sun_color": [0.4, 0.5, 0.3], "fog_color": [0.3, 0.4, 0.2]}, "music_track": "shadowfen_ambient", "pvp_enabled": False},
    {"name": "Sylvaren Forest", "description": "Ancient elven woods where trees whisper and magic flows through the roots.", "climate": "forest", "danger_level": 3, "min_level": 3, "max_level": 10, "connections": ["Shadowfen Bog", "Eldergrove", "Wheatshadow Fields"], "ambient_lighting": {"fog_density": 0.2, "sun_color": [0.7, 0.9, 0.5], "fog_color": [0.6, 0.8, 0.4]}, "music_track": "sylvaren_ambient", "pvp_enabled": False},
    {"name": "Emberfield", "description": "Volcanic plains where rivers of lava carve through blackened stone.", "climate": "volcanic", "danger_level": 5, "min_level": 8, "max_level": 14, "connections": ["Kaltheron Forge", "Ashforge Village", "Wheatshadow Fields"], "ambient_lighting": {"fog_density": 0.3, "sun_color": [1.0, 0.5, 0.2], "fog_color": [0.8, 0.3, 0.1]}, "music_track": "emberfield_ambient", "pvp_enabled": True},
    {"name": "Kaltheron Forge", "description": "A massive underground forge city where dwarven smiths craft legendary weapons.", "climate": "underground", "danger_level": 4, "min_level": 5, "max_level": 12, "connections": ["Emberfield", "Zorathar Depths", "Ironwick"], "ambient_lighting": {"fog_density": 0.1, "sun_color": [0.8, 0.5, 0.1], "fog_color": [0.6, 0.3, 0.0]}, "music_track": "kaltheron_ambient", "pvp_enabled": False},
    {"name": "Frostmead", "description": "Frozen tundra with icy fields sparkling under a weak, pale sun.", "climate": "tundra", "danger_level": 6, "min_level": 10, "max_level": 16, "connections": ["Frosthaven", "Stormcrest Peaks", "Wraithmoor Path"], "ambient_lighting": {"fog_density": 0.4, "sun_color": [0.6, 0.7, 0.9], "fog_color": [0.5, 0.6, 0.8]}, "music_track": "frostmead_ambient", "pvp_enabled": True},
    {"name": "Wraithmoor Crypts", "description": "A sprawling necropolis of crumbling spires and skeletal trees in unnatural gloom.", "climate": "haunted", "danger_level": 8, "min_level": 14, "max_level": 20, "connections": ["Frostmead", "Frosthaven"], "ambient_lighting": {"fog_density": 0.9, "sun_color": [0.2, 0.2, 0.3], "fog_color": [0.1, 0.1, 0.2]}, "music_track": "wraithmoor_ambient", "pvp_enabled": True},
    {"name": "Grimholt Bastion", "description": "A dark fortress where Zorvathax's forces gather for their final assault.", "climate": "dark", "danger_level": 10, "min_level": 18, "max_level": 20, "connections": ["Wraithmoor Crypts", "Zorathar Depths"], "ambient_lighting": {"fog_density": 0.8, "sun_color": [0.3, 0.1, 0.1], "fog_color": [0.2, 0.0, 0.0]}, "music_track": "grimholt_ambient", "pvp_enabled": True},
]

# ============================================================
# MONSTERS (with full loot tables)
# ============================================================
MONSTER_DATA = [
    {"name": "Venomtail Rat", "type": "beast", "level": 1, "region": "Murkfen Hamlet",
     "hp": 30, "strength": 4, "dexterity": 8, "defense": 1, "magic_defense": 1,
     "exp": 10, "behavior": "aggressive", "respawn": 60,
     "loot": [{"id": "venomtail_rat_tails", "chance": 0.5, "quantity": 1, "rarity": "Common"},
              {"id": "kupdun", "chance": 1.0, "quantity": 2, "rarity": "Common"}]},
    {"name": "Shambling Husk", "type": "undead", "level": 2, "region": "Shadowfen Bog",
     "hp": 50, "strength": 8, "dexterity": 2, "defense": 3, "magic_defense": 1,
     "exp": 20, "behavior": "aggressive", "respawn": 90,
     "loot": [{"id": "gloom_silk", "chance": 0.3, "quantity": 1, "rarity": "Uncommon"},
              {"id": "kupdun", "chance": 1.0, "quantity": 5, "rarity": "Common"},
              {"id": "tattered_cloth", "chance": 0.4, "quantity": 1, "rarity": "Common"}]},
    {"name": "Wraithvine Strangler", "type": "plant", "level": 4, "region": "Sylvaren Forest",
     "hp": 65, "strength": 10, "dexterity": 6, "defense": 4, "magic_defense": 3,
     "exp": 35, "behavior": "aggressive", "respawn": 120,
     "loot": [{"id": "wraithvine_tendrils", "chance": 0.4, "quantity": 1, "rarity": "Uncommon"},
              {"id": "kupdun", "chance": 1.0, "quantity": 8, "rarity": "Common"}]},
    {"name": "Emberfang Salamander", "type": "beast", "level": 8, "region": "Emberfield",
     "hp": 120, "strength": 14, "dexterity": 10, "defense": 6, "magic_defense": 4,
     "exp": 70, "behavior": "aggressive", "respawn": 150,
     "loot": [{"id": "ember_scales", "chance": 0.5, "quantity": 2, "rarity": "Uncommon"},
              {"id": "emberbloom", "chance": 0.3, "quantity": 1, "rarity": "Common"},
              {"id": "emberweave_thread", "chance": 0.05, "quantity": 1, "rarity": "Rare"},
              {"id": "kupdun", "chance": 1.0, "quantity": 30, "rarity": "Common"}]},
    {"name": "Cragborn Troll", "type": "giant", "level": 6, "region": "Zorathar Depths",
     "hp": 200, "strength": 18, "dexterity": 4, "defense": 10, "magic_defense": 6,
     "exp": 90, "behavior": "aggressive", "respawn": 180,
     "loot": [{"id": "cragborn_troll_bones", "chance": 0.6, "quantity": 2, "rarity": "Uncommon"},
              {"id": "iron_ore", "chance": 0.4, "quantity": 3, "rarity": "Common"},
              {"id": "cleave_scroll", "chance": 0.05, "quantity": 1, "rarity": "Epic"}]},
    {"name": "Shadowclaw Prowler", "type": "beast", "level": 11, "region": "Frostmead",
     "hp": 180, "strength": 16, "dexterity": 14, "defense": 8, "magic_defense": 5,
     "exp": 110, "behavior": "aggressive", "respawn": 180,
     "loot": [{"id": "shadowclaw_pelts", "chance": 0.5, "quantity": 1, "rarity": "Uncommon"},
              {"id": "zirdun", "chance": 1.0, "quantity": 3, "rarity": "Uncommon"}]},
    {"name": "Spectral Hound", "type": "undead", "level": 13, "region": "Wraithmoor Crypts",
     "hp": 220, "strength": 18, "dexterity": 12, "defense": 10, "magic_defense": 8,
     "exp": 150, "behavior": "aggressive", "respawn": 200,
     "loot": [{"id": "spectral_dust", "chance": 0.6, "quantity": 2, "rarity": "Uncommon"},
              {"id": "spectral_hound_fangs", "chance": 0.3, "quantity": 1, "rarity": "Rare"}]},
    {"name": "Kobold Cavern-Scurry", "type": "humanoid", "level": 3, "region": "Ironwick",
     "hp": 45, "strength": 5, "dexterity": 8, "defense": 2, "magic_defense": 1,
     "exp": 15, "behavior": "aggressive", "respawn": 90,
     "loot": [{"id": "kobold_claws", "chance": 0.5, "quantity": 1, "rarity": "Common"},
              {"id": "kupdun", "chance": 1.0, "quantity": 5, "rarity": "Common"}]},
    {"name": "Grubstake Bandit Chief", "type": "humanoid", "level": 15, "region": "Emberfield",
     "hp": 400, "strength": 22, "dexterity": 14, "defense": 14, "magic_defense": 10,
     "exp": 300, "behavior": "aggressive", "respawn": 600,
     "loot": [{"id": "bandit_sashes", "chance": 0.8, "quantity": 1, "rarity": "Rare"},
              {"id": "grubstake_knife", "chance": 0.3, "quantity": 1, "rarity": "Rare"},
              {"id": "battle_roar_scroll", "chance": 0.05, "quantity": 1, "rarity": "Epic"},
              {"id": "zirdun", "chance": 1.0, "quantity": 50, "rarity": "Uncommon"}]},
    {"name": "Gloomshade Arachnid", "type": "beast", "level": 14, "region": "Shadowfen Bog",
     "hp": 250, "strength": 16, "dexterity": 16, "defense": 8, "magic_defense": 6,
     "exp": 180, "behavior": "aggressive", "respawn": 240,
     "loot": [{"id": "gloom_silk", "chance": 0.7, "quantity": 2, "rarity": "Uncommon"},
              {"id": "gloomfang_dagger", "chance": 0.1, "quantity": 1, "rarity": "Rare"},
              {"id": "kupdun", "chance": 1.0, "quantity": 40, "rarity": "Common"}]},
]

# ============================================================
# BOSS MONSTERS
# ============================================================
BOSS_DATA = [
    {"id": 9001, "name": "Frostfang Behemoth", "type": "boss", "level": 15, "region": "Frostmead",
     "hp": 2000, "strength": 30, "dexterity": 12, "defense": 20, "magic_defense": 15,
     "exp": 1500, "behavior": "boss", "respawn": 7200,
     "skills": ["frost_breath", "glacial_slam", "summon_prowlers"],
     "loot": [{"id": "frostfang_pelt", "chance": 1.0, "quantity": 1, "rarity": "Epic"},
              {"id": "frostgore_shards", "chance": 0.8, "quantity": 3, "rarity": "Rare"},
              {"id": "guldun", "chance": 1.0, "quantity": 3, "rarity": "Epic"}]},
    {"id": 9002, "name": "Wraithvine Overlord", "type": "boss", "level": 17, "region": "Sylvaren Forest",
     "hp": 2800, "strength": 26, "dexterity": 20, "defense": 18, "magic_defense": 20,
     "exp": 2000, "behavior": "boss", "respawn": 7200,
     "skills": ["vine_whip", "spore_burst", "root_cage"],
     "loot": [{"id": "wraithvine_tendrils", "chance": 1.0, "quantity": 5, "rarity": "Rare"},
              {"id": "syltheris_fragments", "chance": 0.6, "quantity": 1, "rarity": "Epic"},
              {"id": "counterattack_scroll", "chance": 0.3, "quantity": 1, "rarity": "Epic"},
              {"id": "guldun", "chance": 1.0, "quantity": 5, "rarity": "Epic"}]},
    {"id": 9003, "name": "Frostgore the Icewraith", "type": "boss", "level": 20, "region": "Frostmead",
     "hp": 4000, "strength": 35, "dexterity": 18, "defense": 25, "magic_defense": 25,
     "exp": 3500, "behavior": "boss", "respawn": 14400,
     "skills": ["blizzard", "ice_lance", "frozen_grave", "wraith_armor"],
     "loot": [{"id": "frostgore_shards", "chance": 1.0, "quantity": 5, "rarity": "Epic"},
              {"id": "frostgore_scepter_fragment", "chance": 0.5, "quantity": 1, "rarity": "Legendary"},
              {"id": "blizzard_scroll", "chance": 0.2, "quantity": 1, "rarity": "Epic"},
              {"id": "guldun", "chance": 1.0, "quantity": 10, "rarity": "Epic"}]},
    {"id": 9004, "name": "Ironscale Drake", "type": "boss", "level": 18, "region": "Grimholt Bastion",
     "hp": 3500, "strength": 32, "dexterity": 14, "defense": 28, "magic_defense": 18,
     "exp": 2800, "behavior": "boss", "respawn": 10800,
     "skills": ["fire_breath", "tail_swipe", "scale_barrier", "dive_bomb"],
     "loot": [{"id": "ironscale_drake_scales", "chance": 1.0, "quantity": 3, "rarity": "Epic"},
              {"id": "mithril_vein", "chance": 0.8, "quantity": 8, "rarity": "Rare"},
              {"id": "desperate_stand_scroll", "chance": 0.25, "quantity": 1, "rarity": "Epic"},
              {"id": "guldun", "chance": 1.0, "quantity": 8, "rarity": "Epic"}]},
    {"id": 9005, "name": "Spectral Hound Alpha", "type": "boss", "level": 20, "region": "Frostmead",
     "hp": 3800, "strength": 30, "dexterity": 24, "defense": 22, "magic_defense": 20,
     "exp": 3200, "behavior": "boss", "respawn": 14400,
     "skills": ["howl_of_despair", "ghostly_charge", "pack_tactics", "spectral_bite"],
     "loot": [{"id": "spectral_hound_fangs", "chance": 1.0, "quantity": 3, "rarity": "Epic"},
              {"id": "spectral_dust", "chance": 1.0, "quantity": 10, "rarity": "Rare"},
              {"id": "adrenaline_rush_scroll", "chance": 0.3, "quantity": 1, "rarity": "Epic"},
              {"id": "guldun", "chance": 1.0, "quantity": 8, "rarity": "Epic"}]},
    {"id": 9006, "name": "Mirethax the Rotlord", "type": "boss", "level": 16, "region": "Shadowfen Bog",
     "hp": 2600, "strength": 22, "dexterity": 10, "defense": 16, "magic_defense": 22,
     "exp": 1800, "behavior": "boss", "respawn": 7200,
     "skills": ["rot_wave", "bog_grasp", "spore_cloud", "decay_aura"],
     "loot": [{"id": "mirethax_spores", "chance": 0.8, "quantity": 2, "rarity": "Epic"},
              {"id": "gloom_silk", "chance": 1.0, "quantity": 5, "rarity": "Uncommon"},
              {"id": "guldun", "chance": 1.0, "quantity": 4, "rarity": "Epic"}]},
    {"id": 9007, "name": "Zorvathax, the Dark Demon Lord", "type": "world_boss", "level": 20, "region": "Grimholt Bastion",
     "hp": 50000, "strength": 50, "dexterity": 30, "defense": 40, "magic_defense": 40,
     "exp": 10000, "behavior": "world_boss", "respawn": 86400,
     "skills": ["soul_drain", "dark_nova", "shadow_legion", "corruption_beam", "fear_aura", "death_grasp", "void_portal"],
     "loot": [{"id": "fateweaver_shard", "chance": 0.03, "quantity": 1, "rarity": "Legendary"},
              {"id": "soulshatter_talisman_fragment", "chance": 0.15, "quantity": 1, "rarity": "Legendary"},
              {"id": "corrupted_essence", "chance": 1.0, "quantity": 5, "rarity": "Epic"},
              {"id": "guldun", "chance": 1.0, "quantity": 50, "rarity": "Epic"},
              {"id": "dark_god_tier_fragment", "chance": 0.01, "quantity": 1, "rarity": "God-Tier"}]},
]

# ============================================================
# NPCs
# ============================================================
NPC_DATA = [
    {"name": "Old Man Thane", "type": "quest_giver", "region": "Murkfen Hamlet", "position": {"x": 10, "y": 0, "z": 5},
     "dialogue": ["Up, Child of the Light! Zorvathax won't wait!", "The swamp holds many secrets. Be wary of the venomous rats."],
     "quests": ["rat_infestation", "duskpetal_gathering"], "faction": "Children of the Light"},
    {"name": "Throg Mudforge", "type": "blacksmith", "region": "Ashforge Village", "position": {"x": -20, "y": 0, "z": 15},
     "dialogue": ["Need your gear mended? I'm the best smith this side of Kaltheron.", "Bring me iron ore and I'll craft you something sturdy."],
     "quests": ["forge_apprentice"], "faction": "Merchants Guild", "services": ["repair", "blacksmithing"]},
    {"name": "Emberly Scorchdeal", "type": "merchant", "region": "Kaltheron Forge", "position": {"x": 25, "y": 0, "z": -10},
     "dialogue": ["Got the finest wares in all the forge-cities!", "Trade with me and you'll get fair prices, friend."],
     "quests": [], "faction": "Merchants Guild", "services": ["shop"]},
    {"name": "Torvald Brightshield", "type": "guild_master", "region": "Frosthaven", "position": {"x": 50, "y": 0, "z": 30},
     "dialogue": ["Welcome to the Adventurers Guild, hero.", "We've got bounties from all across Valtherion."],
     "quests": ["frostfang_patrol", "slay_behemoth"], "faction": "Adventurers Guild"},
    {"name": "Jek Flintkeeper", "type": "guild_liaison", "region": "Murkfen Hamlet", "position": {"x": -5, "y": 0, "z": -8},
     "dialogue": ["The Merchants Guild pays well for deliveries.", "Duskpetal is in high demand. Bring me what you find."],
     "quests": ["duskpetal_haul"], "faction": "Merchants Guild"},
    {"name": "Korrin Wraithbrew", "type": "dark_priest", "region": "Wraithmoor Crypts", "position": {"x": 80, "y": 0, "z": 60},
     "dialogue": ["The dark lord stirs. Will you serve or will you perish?", "Bring me souls and I will bestow Zorvathax's blessing."],
     "quests": ["bog_corruption"], "faction": "Dark Guild"},
]

# ============================================================
# QUESTS
# ============================================================
QUEST_DATA = [
    {"id": "rat_infestation", "name": "Rat Infestation", "description": "Kill 10 Venomtail Rats threatening Murkfen Hamlet.",
     "type": "kill", "difficulty": "easy", "min_level": 1, "region": "Murkfen Hamlet",
     "objectives": [{"type": "kill", "target": "Venomtail Rat", "count": 10}],
     "rewards": {"xp": 50, "currency": {"kupdun": 25}, "items": [{"id": "bread", "name": "Bread Loaf", "quantity": 2}]},
     "giver_npc_name": "Old Man Thane"},
    {"id": "duskpetal_gathering", "name": "Duskpetal Gathering", "description": "Collect 10 Duskpetal herbs from Shadowfen Bog.",
     "type": "collect", "difficulty": "easy", "min_level": 1, "region": "Shadowfen Bog",
     "objectives": [{"type": "collect", "target": "Duskpetal", "count": 10}],
     "rewards": {"xp": 40, "currency": {"kupdun": 30}, "items": [{"id": "potion_vitality", "name": "Potion of Vitality", "quantity": 1}]},
     "giver_npc_name": "Old Man Thane"},
    {"id": "forge_apprentice", "name": "Forge Apprentice", "description": "Craft an Iron Sword for Throg Mudforge.",
     "type": "craft", "difficulty": "easy", "min_level": 3, "region": "Ashforge Village",
     "objectives": [{"type": "craft", "target": "iron_sword", "count": 1}],
     "rewards": {"xp": 60, "currency": {"kupdun": 50}, "recipes": ["emberforge_shield"]},
     "giver_npc_name": "Throg Mudforge"},
    {"id": "frostfang_patrol", "name": "Frostfang Patrol", "description": "Clear 5 Shadowclaw Prowlers from Frostmead.",
     "type": "kill", "difficulty": "moderate", "min_level": 10, "region": "Frostmead",
     "objectives": [{"type": "kill", "target": "Shadowclaw Prowler", "count": 5}],
     "rewards": {"xp": 200, "currency": {"zirdun": 5}, "items": [{"id": "prowlerhide_vest", "name": "Prowlerhide Vest", "quantity": 1}]},
     "giver_npc_name": "Torvald Brightshield"},
    {"id": "slay_behemoth", "name": "Slay the Behemoth", "description": "Defeat the Frostfang Behemoth.",
     "type": "boss", "difficulty": "high", "min_level": 15, "region": "Frostmead",
     "objectives": [{"type": "kill", "target": "Frostfang Behemoth", "count": 1}],
     "rewards": {"xp": 1000, "currency": {"zirdun": 15, "guldun": 1}, "items": [{"id": "spectral_volley_bow", "name": "Spectral Volley Bow", "quantity": 1}]},
     "giver_npc_name": "Torvald Brightshield"},
    {"id": "duskpetal_haul", "name": "Duskpetal Haul", "description": "Deliver 50 Duskpetal to Jek Flintkeeper.",
     "type": "deliver", "difficulty": "easy", "min_level": 1, "region": "Murkfen Hamlet",
     "objectives": [{"type": "deliver", "target": "Duskpetal", "count": 50}],
     "rewards": {"xp": 80, "currency": {"kupdun": 200}},
     "giver_npc_name": "Jek Flintkeeper"},
    {"id": "bog_corruption", "name": "Bog Corruption", "description": "Plant 3 necrotic totems in Shadowfen Bog.",
     "type": "quest", "difficulty": "moderate", "min_level": 8, "region": "Shadowfen Bog",
     "objectives": [{"type": "use", "target": "Necrotic Totem", "count": 3}],
     "rewards": {"xp": 300, "currency": {"zirdun": 10}, "alignment": {"dark": 200}},
     "giver_npc_name": "Korrin Wraithbrew", "duration_hours": 72},
]

# ============================================================
# GUILD MISSIONS
# ============================================================
GUILD_MISSIONS = {
    "Adventurers": [
        {"id": "g_rat_infestation", "name": "Rat Infestation", "description": "Kill 10 Venomtail Rats", "reward": 20, "difficulty": "easy", "target": 10},
        {"id": "g_frostfang_patrol", "name": "Frostfang Patrol", "description": "Clear 5 Shadowclaw Prowlers", "reward": 150, "difficulty": "moderate", "target": 5},
        {"id": "g_slay_behemoth", "name": "Slay the Behemoth", "description": "Defeat Frostfang Behemoth", "reward": 700, "difficulty": "high", "target": 1},
        {"id": "g_luminant_guard", "name": "Luminant Guard", "description": "Defend Aurelith from Dark forces", "reward": 350, "difficulty": "high", "target": 1},
        {"id": "g_pyreclaw_prowl", "name": "Pyreclaw Prowl", "description": "Hunt 8 Pyreclaw beasts", "reward": 250, "difficulty": "moderate", "target": 8},
    ],
    "Merchants": [
        {"id": "g_duskpetal_haul", "name": "Duskpetal Haul", "description": "Deliver 50 Duskpetal", "reward": 200, "difficulty": "easy", "target": 50},
        {"id": "g_emberbloom_stock", "name": "Emberbloom Stock", "description": "Deliver 40 Emberbloom", "reward": 220, "difficulty": "moderate", "target": 40},
        {"id": "g_iron_ore_shipment", "name": "Iron Ore Shipment", "description": "Deliver 100 Iron Ore", "reward": 400, "difficulty": "moderate", "target": 100},
        {"id": "g_trade_route", "name": "Trade Route Protection", "description": "Clear 10 Bandit Camps", "reward": 500, "difficulty": "high", "target": 10},
    ],
    "Assassins": [
        {"id": "g_silent_farmer", "name": "Silent Farmer", "description": "Eliminate Farmer Jorn", "reward": 100, "difficulty": "easy", "target": 1},
        {"id": "g_forge_spy", "name": "Forge Spy", "description": "Eliminate Kaltheron spy", "reward": 500, "difficulty": "high", "target": 1},
        {"id": "g_overseer_hit", "name": "Overseer Hit", "description": "Take down Overseer at Thornskull", "reward": 350, "difficulty": "moderate", "target": 1},
    ],
    "Dark": [
        {"id": "g_bog_corruption", "name": "Bog Corruption", "description": "Plant necrotic totems in Shadowfen", "reward": 400, "difficulty": "moderate", "duration_hours": 72, "target": 1},
        {"id": "g_wraith_lord_ritual", "name": "Wraith Lord Ritual", "description": "Summon a Wraith Lord", "reward": 800, "difficulty": "high", "duration_hours": 120, "target": 1},
        {"id": "g_tundra_desecration", "name": "Tundra Desecration", "description": "Desecrate holy sites in Frostmead", "reward": 600, "difficulty": "moderate", "duration_hours": 96, "target": 1},
    ],
    "Order": [
        {"id": "g_protect_caravan", "name": "Protect the Caravan", "description": "Guard the Murkfen Caravan", "reward": 200, "difficulty": "moderate", "target": 1},
        {"id": "g_purge_crypts", "name": "Purge the Crypts", "description": "Clear 20 undead from Wraithmoor", "reward": 500, "difficulty": "high", "target": 20},
    ],
}

# ============================================================
# CURRENCY
# ============================================================
CURRENCY = {
    "kupdun": {"name": "Kupdun", "tier": 1, "icon": "kupdun_coin", "max_stack": 999},
    "zirdun": {"name": "Zirdun", "tier": 2, "icon": "zirdun_coin", "conversion": 100, "max_stack": 99},
    "guldun": {"name": "Guldun", "tier": 3, "icon": "guldun_coin", "conversion": 10000, "max_stack": 99},
}

# ============================================================
# LUCK ENHANCERS
# ============================================================
LUCK_ENHANCERS = [
    {"id": "rabbits_foot_talisman", "name": "Rabbit's Foot Talisman", "rarity": "Uncommon", "luck_bonus": 3,
     "source": "Swiftantler Deer (5% drop), Murkfen Hamlet shop",
     "description": "A small, weathered paw said to nudge fate in your favor."},
    {"id": "four_leaf_clover_pendant", "name": "Four-Leaf Clover Pendant", "rarity": "Uncommon", "luck_bonus": 4,
     "source": "Sylvaren forests (10% harvest), Merchants Guild (50 Kupdun)",
     "description": "A rare bloom, its leaves humming with subtle luck."},
    {"id": "luminant_coin", "name": "Luminant Coin", "rarity": "Rare", "luck_bonus": 7,
     "source": "Torchlight Overlord (15% drop), Alchemist Level 5 craft",
     "description": "A glowing coin from a forgotten hoard, radiating fortune."},
    {"id": "wraithmoor_dice", "name": "Wraithmoor Dice", "rarity": "Epic", "luck_bonus": 10,
     "source": "Hidden chest in Wraithmoor Crypts, Assassins Guild reward",
     "description": "Bone-carved dice, rattling with the luck of the damned."},
    {"id": "fateweaver_shard", "name": "Zarathyn's Fateweaver Shard", "rarity": "Legendary", "luck_bonus": 15,
     "source": "Zorvathax (3% drop, 3 fragments to assemble), Enchanter Level 10",
     "description": "A crystalline shard pulsing with Zorvathax's defied fate."},
]

# ============================================================
# STARTER INVENTORY
# ============================================================
STARTER_INVENTORY = [
    {"id": "wooden_club", "name": "Wooden Club", "quantity": 1, "weight": 5, "type": "weapon", "rarity": "Common"},
    {"id": "tattered_shirt", "name": "Tattered Shirt", "quantity": 1, "weight": 2, "type": "armor", "rarity": "Common"},
    {"id": "bread", "name": "Bread Loaf", "quantity": 3, "weight": 0.5, "type": "consumable", "rarity": "Common"},
]

# ============================================================
# CRAFTING STATIONS BY REGION
# ============================================================
CRAFTING_STATIONS = [
    {"region": "Kaltheron Forge", "station": "Forge", "job_types": ["blacksmithing", "enchanting"]},
    {"region": "Ashforge Village", "station": "Anvil", "job_types": ["blacksmithing"]},
    {"region": "Duskwind", "station": "Arcane Crucible", "job_types": ["alchemy", "enchanting"]},
    {"region": "Drakemire", "station": "Rune Table", "job_types": ["enchanting"]},
    {"region": "Shadowfen Bog", "station": "Tinker's Bench", "job_types": ["fletching", "leatherworking"]},
    {"region": "Thornskull Hold", "station": "Smuggler's Forge", "job_types": ["fletching", "leatherworking"]},
    {"region": "Wheatshadow Fields", "station": "Carver's Stall", "job_types": ["fletching"]},
    {"region": "Eldergrove", "station": "Hunter's Lodge", "job_types": ["fletching", "leatherworking"]},
    {"region": "Brighthaven", "station": "Altar", "job_types": ["cooking", "alchemy"]},
    {"region": "Sylvaren Forest", "station": "Sanctum", "job_types": ["enchanting", "alchemy"]},
    {"region": "Ironwick", "station": "Workshop", "job_types": ["blacksmithing", "fletching", "leatherworking"]},
]
