"""baseline schema from models

Revision ID: f23dd71e6f47
Revises: 
Create Date: 2026-08-06 11:43:36.056878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23dd71e6f47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=50), nullable=True),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('item_rarity', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_listings_id'), 'auction_listings', ['id'], unique=False)
    op.create_index(op.f('ix_auction_listings_item_id'), 'auction_listings', ['item_id'], unique=False)
    op.create_index(op.f('ix_auction_listings_seller_id'), 'auction_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_auction_listings_status'), 'auction_listings', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_channel'), 'chat_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('crafting_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_item_id', sa.String(length=100), nullable=False),
    sa.Column('result_quantity', sa.Integer(), nullable=True),
    sa.Column('result_rarity', sa.String(length=20), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('required_tools', sa.JSON(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('crafting_time_seconds', sa.Integer(), nullable=True),
    sa.Column('experience_gain', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('location_required', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crafting_recipes_id'), 'crafting_recipes', ['id'], unique=False)
    op.create_table('dungeons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('current_location', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('spawned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_players', sa.Integer(), nullable=True),
    sa.Column('bosses', sa.JSON(), nullable=True),
    sa.Column('rewards', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeons_id'), 'dungeons', ['id'], unique=False)
    op.create_index(op.f('ix_dungeons_name'), 'dungeons', ['name'], unique=False)
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('likeness', sa.Integer(), nullable=True),
    sa.Column('treasury', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emblem', sa.JSON(), nullable=True),
    sa.Column('hall_region', sa.String(length=100), nullable=True),
    sa.Column('active_missions', sa.JSON(), nullable=True),
    sa.Column('completed_missions', sa.JSON(), nullable=True),
    sa.Column('member_capacity', sa.Integer(), nullable=True),
    sa.Column('vault', sa.JSON(), nullable=True),
    sa.Column('hall', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_id'), 'guilds', ['id'], unique=False)
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=True)
    op.create_table('item_blueprints',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=True),
    sa.Column('max_stack', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('value_currency', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('enchantments', sa.JSON(), nullable=True),
    sa.Column('crafted_by', sa.Integer(), nullable=True),
    sa.Column('instance_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('shop_type', sa.String(length=50), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('restock_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_restock', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_accepted', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('monster_type', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('magic_defense', sa.Integer(), nullable=True),
    sa.Column('attack_power', sa.Integer(), nullable=True),
    sa.Column('experience_reward', sa.Integer(), nullable=True),
    sa.Column('loot_table', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('behavior', sa.String(length=50), nullable=True),
    sa.Column('respawn_time_seconds', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('spawned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_id'), 'monsters', ['id'], unique=False)
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('npc_type', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('rotation_yaw', sa.Float(), nullable=True),
    sa.Column('dialogue', sa.JSON(), nullable=True),
    sa.Column('quests', sa.JSON(), nullable=True),
    sa.Column('faction', sa.String(length=50), nullable=True),
    sa.Column('likeness_threshold', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_id'), 'npcs', ['id'], unique=False)
    op.create_index(op.f('ix_npcs_name'), 'npcs', ['name'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('emblem', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('loot_mode', sa.String(length=20), nullable=True),
    sa.Column('experience_share', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=True)
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quest_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('guild_required', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('rewards', sa.JSON(), nullable=True),
    sa.Column('giver_npc_id', sa.Integer(), nullable=True),
    sa.Column('giver_npc_name', sa.String(length=100), nullable=True),
    sa.Column('follow_up_quest_id', sa.Integer(), nullable=True),
    sa.Column('is_repeatable', sa.Boolean(), nullable=True),
    sa.Column('is_story_quest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('danger_level', sa.Integer(), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('connections', sa.JSON(), nullable=True),
    sa.Column('ambient_lighting', sa.JSON(), nullable=True),
    sa.Column('music_track', sa.String(length=100), nullable=True),
    sa.Column('pvp_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.create_table('spawn_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('respawn_interval', sa.Integer(), nullable=True),
    sa.Column('max_spawn_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spawn_points_id'), 'spawn_points', ['id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=True),
    sa.Column('bounds', sa.JSON(), nullable=True),
    sa.Column('npcs', sa.JSON(), nullable=True),
    sa.Column('monsters', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('stat_points', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('species_variant', sa.String(length=50), nullable=True),
    sa.Column('alignment_points', sa.JSON(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('luck', sa.Integer(), nullable=True),
    sa.Column('luck_unlocked', sa.Boolean(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_mana', sa.Integer(), nullable=True),
    sa.Column('max_mana', sa.Integer(), nullable=True),
    sa.Column('current_stamina', sa.Integer(), nullable=True),
    sa.Column('max_stamina', sa.Integer(), nullable=True),
    sa.Column('hunger', sa.Integer(), nullable=True),
    sa.Column('current_region', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('rotation_yaw', sa.Float(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('hotbar', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('currency', sa.JSON(), nullable=True),
    sa.Column('job_class', sa.String(length=50), nullable=True),
    sa.Column('job_level', sa.Integer(), nullable=True),
    sa.Column('sub_class', sa.String(length=50), nullable=True),
    sa.Column('main_class', sa.String(length=50), nullable=True),
    sa.Column('crafting_levels', sa.JSON(), nullable=True),
    sa.Column('guilds', sa.JSON(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('active_quests', sa.JSON(), nullable=True),
    sa.Column('completed_quests', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('known_recipes', sa.JSON(), nullable=True),
    sa.Column('friends', sa.JSON(), nullable=True),
    sa.Column('ignored_players', sa.JSON(), nullable=True),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('combat_state', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_spawn_points_id'), table_name='spawn_points')
    op.drop_table('spawn_points')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_npcs_name'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_id'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('item_blueprints')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_index(op.f('ix_guilds_id'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_dungeons_name'), table_name='dungeons')
    op.drop_index(op.f('ix_dungeons_id'), table_name='dungeons')
    op.drop_table('dungeons')
    op.drop_index(op.f('ix_crafting_recipes_id'), table_name='crafting_recipes')
    op.drop_table('crafting_recipes')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_channel'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_auction_listings_status'), table_name='auction_listings')
    op.drop_index(op.f('ix_auction_listings_seller_id'), table_name='auction_listings')
    op.drop_index(op.f('ix_auction_listings_item_id'), table_name='auction_listings')
    op.drop_index(op.f('ix_auction_listings_id'), table_name='auction_listings')
    op.drop_table('auction_listings')
    # ### end Alembic commands ###
